# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: no-commit-to-branch
      - id: detect-private-key
      - id: check-merge-conflict
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        additional_dependencies: [toml==0.10.2]
        args: [--in-place, --parallel]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bandit==4.1.1
          - flake8-bugbear==23.5.9
          - flake8-builtins==2.0.1
          - flake8-coding==1.3.2
          - flake8-commas==2.1.0
          - flake8-comprehensions==3.12.0
          - flake8-docstrings==1.7.0
          - flake8-expression-complexity==0.0.11
          - flake8-import-order==0.18.2
          - flake8-isort==6.0.0
          - flake8-pep3101==2.0.0
          - flake8-plugin-utils==1.3.2
          - flake8-polyfill==1.0.2
          - flake8-pytest==1.4
          - flake8-pytest-style==1.7.2
          - flake8-requirements==1.7.8
          - flake8-simplify==0.20.0
          - flake8-use-fstring==1.4
          - pep8-naming==0.13.3
  - repo: https://github.com/PyCQA/pylint
    rev: v2.17.4
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests==2.28.11.5
          - types-toml==0.10.8.20240310
          - types-setuptools==69.2.0.20240317
